/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prontidão (banco + Redis). Usada no healthcheck do compose. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pronto */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Dependência fora do ar */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista eventos (público) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["EventSummary"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lotes à venda de um evento, um por tipo de ingresso (público) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["PublicBatchLine"][];
                        };
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cria um pedido (público, sem login)
         * @description Reserva atomicamente o estoque do lote e cria o pedido `pending`. Exige `Idempotency-Key`:
         *     o mesmo par chave + corpo devolve o MESMO pedido (200 + `Idempotent-Replay: true`),
         *     cobrindo clique duplo e reenvio por queda de conexão. A mesma chave com corpo diferente
         *     responde 422 `idempotency_payload_mismatch`. O pedido expira (e a reserva volta ao lote)
         *     após `RESERVATION_TTL_MINUTES` sem pagamento.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Gere um UUID por tentativa de compra e reuse nos reenvios. */
                    "Idempotency-Key": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrderInput"];
                };
            };
            responses: {
                /** @description Replay idempotente (mesmo pedido, header `Idempotent-Replay`) */
                200: {
                    headers: {
                        "Idempotent-Replay"?: "true";
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Order"];
                        };
                    };
                };
                /** @description Pedido criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Order"];
                        };
                    };
                };
                /** @description `Idempotency-Key` ausente (code `idempotency_key_required`). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Lote esgotado (`sold_out`) ou inativo (`batch_inactive`). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Validação (CPF, e-mail, quantidade...) ou `idempotency_payload_mismatch`. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Limite por IP (`ORDERS_RATE_LIMIT_PER_MINUTE`, 0 desliga). Honre `Retry-After`. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Chave de idempotência em processamento; tente de novo em instantes. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Situação de um pedido (público; o UUID é o segredo de acesso) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Order"];
                        };
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aviso do gateway de pagamento (aprovado, recusado ou reembolsado)
         * @description Idempotente por `event_id`; tolera avisos repetidos e fora de ordem; responde rápido
         *     (só estado + outbox, sem e-mail/PDF/financeiro na requisição).
         *     Pedido inexistente => 404 sem gravar o aviso.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PaymentWebhookInput"];
                };
            };
            responses: {
                /** @description Processado (ou já processado antes) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error"];
                404: components["responses"]["Error"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login de administrador (com throttle) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["AuthPayload"];
                        };
                    };
                };
                422: components["responses"]["ValidationError"];
                429: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoga o token atual */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuário autenticado */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Painel de vendas por evento e lote (admin)
         * @description Lê só os contadores do lote (O(nº de lotes), nunca COUNT em `orders`), com cache de ~1s
         *     e `ETag`/`If-None-Match` (304 quando nada mudou): ~30 pessoas podem atualizar a cada
         *     poucos segundos sem degradar a compra.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    "If-None-Match"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        ETag?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardSnapshot"];
                    };
                };
                /** @description Sem mudanças */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dev/gateway/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulador do gateway (admin; só com ENABLE_DEV_TOOLS=true)
         * @description Dispara avisos assinados para o webhook real. Ações: `approve`, `decline`, `refund`,
         *     `duplicate` (4.2a: mesmo aviso N vezes em paralelo), `out-of-order` (4.2b: refunded antes
         *     de approved) e `retry-on-timeout` (4.2c: o gateway desiste da resposta e reenvia o mesmo aviso).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    action: "approve" | "decline" | "refund" | "duplicate" | "out-of-order" | "retry-on-timeout";
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GatewaySimulationInput"];
                };
            };
            responses: {
                /** @description Resultado de cada chamada ao webhook */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            result: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["Error"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @description Código estável, ex.: sold_out, batch_inactive, validation_failed, idempotency_payload_mismatch, rate_limited, forbidden. */
                code: string;
                message: string;
                /** @description Presente em erros de validação (422). */
                fields?: {
                    [key: string]: string[];
                };
                /** @description Segundos sugeridos antes de nova tentativa (429/503). */
                retry_after?: number;
            };
        };
        EventSummary: {
            id: number;
            name: string;
            image_url?: string | null;
        };
        /** @description Uma linha por tipo de ingresso, sempre com o lote ativo daquele tipo. */
        PublicBatchLine: {
            ticket_type_id: number;
            /** @description Nome do TIPO de ingresso (ex.: Pista). */
            name: string;
            /** @description Id do lote ativo; null se não houver lote ativo. */
            id: number | null;
            batch_label?: string | null;
            price_cents: number | null;
            available: number;
            sold_out: boolean;
        };
        BatchSummary: components["schemas"]["PublicBatchLine"];
        /** @enum {string} */
        OrderStatus: "pending" | "paid" | "declined" | "expired" | "refunded" | "refund_required";
        Order: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["OrderStatus"];
            batch_id: number;
            batch_name: string;
            quantity: number;
            total_cents: number;
            /** @description E-mail parcialmente mascarado (ex.: ma***@exemplo.com). O documento nunca é devolvido. */
            buyer_email: string;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        BuyerInput: {
            name: string;
            /** Format: email */
            email: string;
            /** @description CPF válido, com ou sem máscara. */
            document: string;
        };
        TicketHolderInput: {
            name: string;
            /** Format: email */
            email: string;
        };
        CreateOrderInput: {
            batch_id: number;
            quantity: number;
            buyer: components["schemas"]["BuyerInput"];
            /** @description OPCIONAL. Titular de cada ingresso; se informado, o tamanho deve ser igual a `quantity`. Ausente => o titular é o comprador. */
            tickets?: components["schemas"]["TicketHolderInput"][];
        };
        User: {
            id: number;
            name: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "customer" | "admin";
        };
        LoginInput: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        AuthPayload: {
            user: components["schemas"]["User"];
            /** @description Token opaco (Sanctum). Enviar como 'Authorization: Bearer <token>'. */
            token: string;
        };
        PaymentWebhookInput: {
            /** @description Identificador próprio do aviso. O mesmo event_id enviado N vezes tem efeito UMA vez. */
            event_id: string;
            /** Format: uuid */
            order_id: string;
            /** @enum {string} */
            type: "approved" | "declined" | "refunded";
            /** Format: date-time */
            occurred_at: string;
        };
        GatewaySimulationInput: {
            /** Format: uuid */
            order_id: string;
            /** @description Só para `duplicate` (padrão 5). */
            times?: number;
        };
        DashboardBatch: {
            id: number;
            name: string;
            price_cents: number;
            total: number;
            sold: number;
            /** @description Aguardando pagamento (reservado). */
            pending: number;
            available: number;
            revenue_cents: number;
        };
        DashboardEvent: {
            id: number;
            name: string;
            totals: {
                sold: number;
                pending: number;
                available: number;
                revenue_cents: number;
            };
            batches: components["schemas"]["DashboardBatch"][];
        };
        DashboardSnapshot: {
            /** Format: date-time */
            generated_at: string;
            events: components["schemas"]["DashboardEvent"][];
            /** @description Outbox do pós-pagamento. `failed` > 0 exige `php artisan outbox:retry --all-failed`. */
            jobs: {
                pending: number;
                running: number;
                failed: number;
            };
        };
        PaginationLinks: {
            first?: string | null;
            last?: string | null;
            prev?: string | null;
            next?: string | null;
        };
        PaginationMeta: {
            current_page?: number;
            per_page?: number;
            total?: number;
            last_page?: number;
        };
    };
    responses: {
        /** @description Erro padronizado */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Sem token ou token inválido (code `unauthenticated`). */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Autenticado, mas não é administrador (code `forbidden`). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Corpo inválido (`fields` traz o detalhe por campo). */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
